### Белычев Артем


### Задание 1


In [2]:
import numpy as np


In [4]:
a=np.array(
    [[1,6],
    [2,8],
    [3,11],
    [3,10],
    [1,7]]
    );


mean_a = np.array([])
for k,i in enumerate(a[0]):
    mean_a = np.append(mean_a,a[:,k].mean())

mean_a

array([2. , 8.4])

### Задание 2

In [5]:
a_centered = a - mean_a
a_centered


array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [6]:
a_centered_sp = np.dot(a_centered.T[0],a_centered.T[1])
print(a_centered_sp)
b = len(a)-1
print(b)
print(f'{(a_centered_sp/b)}')

8.0
4
2.0


### Задание 4

In [11]:
a=np.transpose(a)
print(a)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [12]:
np.cov(a)

array([[1. , 2. ],
       [2. , 4.3]])

### Работа с данными в Pandas

### Задание 1

In [10]:
import pandas as pd

In [14]:
authors = pd.DataFrame();
authors['author_id'] = [1, 2, 3];
authors['author_name'] = ['Тургенев', 'Чехов', 'Островский'];

book = pd.DataFrame();
book['author_id'] = [1, 1, 1, 2, 2, 3, 3];
book['book_title'] = ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'];
book['price'] = [450, 300, 350, 500, 450, 370, 290];

In [ ]:
### Задание 2

In [13]:
authors_price = pd.merge(authors,book,how = 'inner', on = 'author_id');
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### ЗАдание 3

In [15]:
top5 = authors_price.nlargest(5,'price');
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [16]:
authors_stat = authors_price.groupby('author_name').agg({'price':('max','min','mean')}).round(2)
authors_stat.rename(columns = {'min':'min_price','max':'max_price','mean':'mean_price'}, inplace=True)
authors_stat.columns = authors_stat.columns.droplevel(0)
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290      330.00
Тургенев           450        300      366.67
Чехов              500        450      475.00

### Задание 5

In [17]:
authors_price['cover']=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [19]:
?pd.pivot_table

In [20]:
book_info = pd.pivot_table(authors_price[['author_name','price','cover']],index='author_name', dropna=False, columns=['cover'],fill_value='0',aggfunc=np.sum)

In [21]:
book_info.columns = book_info.columns.droplevel(0)
book_info

cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950

In [22]:
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')

book_info2

cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950